export const SET_USER_DATA = "SET_USER_DATA";
export const SET_JWT_TOKEN = "SET_JWT_TOKEN";
export const SET_REFRESH_TOKEN = "SET_REFRESH_TOKEN";
export const RESET_AUTH_DATA = "RESET_AUTH_DATA";
export const SET_IS_ACCOUNT_ACTIVE = "SET_IS_ACCOUNT_ACTIVE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
